"""Central UI intent catalog for Blattwerk shortcut semantics."""

from __future__ import annotations


class UiIntent:
    PREVIEW_PREV_PAGE = "preview.prev_page"
    PREVIEW_NEXT_PAGE = "preview.next_page"
    PREVIEW_SCROLL_UP = "preview.scroll_up"
    PREVIEW_SCROLL_DOWN = "preview.scroll_down"
    PREVIEW_TOGGLE_CONTRAST = "preview.toggle_contrast"
    PREVIEW_CYCLE_DESIGN = "preview.cycle_design"
    PREVIEW_BLACK_BOTH = "preview.black_both"
    PREVIEW_PAGE_A4 = "preview.page_a4"
    PREVIEW_PAGE_A5 = "preview.page_a5"
    PREVIEW_FIT_WIDTH = "preview.fit_width"
    PREVIEW_FIT_PAGE = "preview.fit_page"
    PREVIEW_LAYOUT_SINGLE = "preview.layout_single"
    PREVIEW_LAYOUT_STRIP = "preview.layout_strip"
    PREVIEW_LAYOUT_STACK = "preview.layout_stack"
    PREVIEW_ZOOM_OUT = "preview.zoom_out"
    PREVIEW_ZOOM_IN = "preview.zoom_in"
    PREVIEW_ZOOM_OUT_NUMPAD = "preview.zoom_out_numpad"
    PREVIEW_ZOOM_IN_NUMPAD = "preview.zoom_in_numpad"
    PREVIEW_TOGGLE_MODE = "preview.toggle_mode"
    PREVIEW_REFRESH = "preview.refresh"

    GLOBAL_EXPORT = "global.export"
    GLOBAL_HELP_PREVIEW = "global.help_preview"
    GLOBAL_OPEN_FILE = "global.open_file"
    GLOBAL_NEW_FILE = "global.new_file"
    GLOBAL_OPEN_FILE_CTRL = "global.open_file_ctrl"
    GLOBAL_SAVE_AS = "global.save_as"
    GLOBAL_SETTINGS = "global.settings"
    GLOBAL_VIEW_PREVIEW = "global.view_preview"
    GLOBAL_VIEW_BOTH = "global.view_both"
    GLOBAL_VIEW_EDITOR = "global.view_editor"
    GLOBAL_CYCLE_THEME = "global.cycle_theme"
    GLOBAL_CYCLE_FONT = "global.cycle_font"
    GLOBAL_OPEN_RECENT = "global.open_recent"
    GLOBAL_DEBUG_OVERLAY = "global.debug_overlay"
    GLOBAL_DEBUG_OFFLINE = "global.debug_offline"
    GLOBAL_ESCAPE = "global.escape"
